directories:
  output: bin
  buildResources: build
appId: com.verifactu.connector
productName: VeriFactu Connector
artifactName: VeriFactu-Connector-Setup-${version}.${ext}
files:
  - filter:
      - '**/*'
      - '!bin/**'
      - '!config.json'
      - '!**/*.map'
      - '!**/tests/**'
      - '!**/test/**'
      - '!**/docs/**'
      - '!**/examples/**'
asar: true
compression: maximum
win:
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: true
  perMachine: false
  allowToChangeInstallationDirectory: false
  deleteAppDataOnUninstall: true
electronVersion: 31.7.7
