directories:
  output: bin
  buildResources: build
appId: com.verifactu.connector
productName: VeriFactu Connector
artifactName: VeriFactu-Connector-Setup-${version}.${ext}
files:
  - filter:
      - '**/*'
      - '!bin/**'
      - '!**/*.map'
      - '!**/tests/**'
      - '!**/test/**'
      - '!**/docs/**'
      - '!**/examples/**'
asar: true
compression: maximum
win:
  target:
    - target: nsis
      arch:
        - x64
    - target: nsis-web
      arch:
        - x64
nsis:
  include: build/installer.nsh
  oneClick: true
  perMachine: false
  allowToChangeInstallationDirectory: false
  deleteAppDataOnUninstall: true
  runAfterFinish: true
  createStartMenuShortcut: true
  createDesktopShortcut: always
  shortcutName: VeriFactu Connector
  uninstallDisplayName: VeriFactu Connector
nsisWeb:
  include: build/installer.nsh
  oneClick: true
  artifactName: VeriFactu-Connector-Web-Setup-${version}.${ext}
  appPackageUrl: http://127.0.0.1:8080/verifactu-printer-connector-1.0.0-x64.nsis.7z
  differentialPackage: true
  runAfterFinish: true
  createStartMenuShortcut: true
  createDesktopShortcut: always
  shortcutName: VeriFactu Connector
electronVersion: 38.0.0
