<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="https://prewww1.aeat.es/wisedi/sif/FacturaJustificanteV1SOAP" xmlns:sif="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/desarrolladores/wisesdi/sif/schemas/FacturaJustificanteV1.xsd" targetNamespace="https://prewww1.aeat.es/wisedi/sif/FacturaJustificanteV1SOAP">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/desarrolladores/wisesdi/sif/schemas/FacturaJustificanteV1.xsd" elementFormDefault="qualified">
            <xs:include schemaLocation="FacturaJustificanteV1.xsd"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="SuministroFacturasJustificantesRequest">
        <wsdl:part name="SuministroFacturasJustificantes" element="sif:SuministroFacturasJustificantes"/>
    </wsdl:message>
    <wsdl:message name="SuministroFacturasJustificantesResponse">
        <wsdl:part name="RespuestaSuministro" element="sif:RespuestaSuministro"/>
    </wsdl:message>
    <wsdl:portType name="SuministroFacturasJustificantesPortType">
        <wsdl:operation name="SuministroFacturasJustificantes">
            <wsdl:input message="tns:SuministroFacturasJustificantesRequest"/>
            <wsdl:output message="tns:SuministroFacturasJustificantesResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="SuministroFacturasJustificantesBinding" type="tns:SuministroFacturasJustificantesPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="SuministroFacturasJustificantes">
            <soap:operation soapAction="https://prewww1.aeat.es/wisedi/sif/SuministroFacturasJustificantes"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="SuministroFacturasJustificantesService">
        <wsdl:port name="SuministroFacturasJustificantesPort" binding="tns:SuministroFacturasJustificantesBinding">
            <soap:address location="http://localhost:8000/sif"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>