name: CI verifactu

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-bff:
    name: Backend BFF
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: verifactu_test
        # GitHub esperará a que el healthcheck sea "healthy"
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 30
          --health-start-period 20s

    env:
      # OJO: host = postgres (nombre del servicio), no localhost
      DATABASE_URL: postgres://test:test@postgres:5432/verifactu_test
      NODE_ENV: test
      PGUSER: test
      PGPASSWORD: test
      PGHOST: postgres
      PGPORT: "5432"
      PGDATABASE: verifactu_test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar deps
        working-directory: verifactu-bff
        run: npm ci

      - name: Lint
        working-directory: verifactu-bff
        run: npm run lint --if-present

      - name: Tipos
        working-directory: verifactu-bff
        run: npm run typecheck --if-present

      - name: Migraciones (si aplica)
        working-directory: verifactu-bff
        run: npm run migration:run --if-present || true

      - name: Tests e2e (Nest + supertest)
        working-directory: verifactu-bff
        run: npm run test:e2e

  backend-connector:
    name: Backend Connector
    runs-on: ubuntu-latest
    needs: backend-bff

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar deps
        working-directory: verifactu-connector
        run: npm ci

      - name: Lint
        working-directory: verifactu-connector
        run: npm run lint --if-present
        continue-on-error: true

      - name: Tipos
        working-directory: verifactu-connector
        run: npm run typecheck --if-present
        continue-on-error: true

      - name: Tests
        working-directory: verifactu-connector
        run: npm test --if-present
        continue-on-error: true

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: No Node steps (no package.json)
        if: ${{ hashFiles('verifactu-ui/package.json') == '' }}
        run: echo "No package.json in verifactu-ui; skipping Node steps."

      - name: Install deps
        if: ${{ hashFiles('verifactu-ui/package.json') != '' }}
        working-directory: verifactu-ui
        run: npm ci

      - name: Lint
        if: ${{ hashFiles('verifactu-ui/package.json') != '' }}
        working-directory: verifactu-ui
        run: npm run lint --if-present
        continue-on-error: true

      - name: Tests
        if: ${{ hashFiles('verifactu-ui/package.json') != '' }}
        working-directory: verifactu-ui
        run: npm test --if-present
        continue-on-error: true

  electron:
    name: Electron
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: No Node steps (no package.json)
        if: ${{ hashFiles('verifactu-printer-connector/package.json') == '' }}
        run: echo "No package.json in verifactu-printer-connector; skipping."

      - name: Install deps
        if: ${{ hashFiles('verifactu-printer-connector/package.json') != '' }}
        working-directory: verifactu-printer-connector
        run: npm ci

      - name: Lint
        if: ${{ hashFiles('verifactu-printer-connector/package.json') != '' }}
        working-directory: verifactu-printer-connector
        run: npm run lint --if-present
        continue-on-error: true

      - name: Tests
        if: ${{ hashFiles('verifactu-printer-connector/package.json') != '' }}
        working-directory: verifactu-printer-connector
        run: npm test --if-present
        continue-on-error: true
